[phases.setup]
nixPkgs = ["python310", "pip"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn src.app:server --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120"

